

server.port=8080

affordmed.base-url=http://4.224.186.213/evaluation-service

affordmed.company-name=YOUR_COMPANY_NAME
affordmed.owner-name=Divyansh
affordmed.roll-no=2301921690027
affordmed.owner-email=csh23023@glbitm.ac.in
affordmed.access-code=xxkJnk