server.port=8080

# Affordmed Test Server Base URL
affordmed.base-url=http://4.224.186.213/evaluation-service

# Your credentials (fill in from your email)
affordmed.company-name=YOUR_COMPANY_NAME
affordmed.owner-name=YOUR_NAME
affordmed.roll-no=YOUR_ROLL_NO
affordmed.owner-email=YOUR_EMAIL
affordmed.access-code=YOUR_ACCESS_CODE
